### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by clytemnestra** [cecilia-sanare/Puppets#3]
Hello, we tried to fiddle a bit with this one, but don't really understand that delay part. I first do /pm beesknees 1 which echoes a number and then /pm beesknees -[that number] and seems to work, but not entirely sure if this is the right way. Also, why are pats disabled? Thank you for this, had quite the fun with it so far ♥

**Comment by cecilia-sanare** [comment]
I'm honestly surprised you've invested the time to figure out how some of the commands work! This is still a WIP plugin hence some of the extra messages I'm sending and the blatant lie about it working in linkshells. lol

So I suspect you've already figured out a lot of this based on your message, but I'll go through it step by step just for clarity.
Whoever is party leader is automatically the puppet master. Only the puppet master has their commands respected by other clients (and themselves for that matter). That said it seems like you're using it correctly.

So `/pm [emote] [delay]`. [emote] is fairly self explanatory and you already figured that bit out.
[delay] is where a lot of the magic happens. Basically the delay is how long you want it to wait before executing the command.
This is necessary due to server latency, however in the future I'm going to likely default this to 1s.

```
/pm beesknees 0.5
[PM] beesknees @ 8/16/2022 3:02:45 PM // Date + Time its going to execute the command
126.0185 // Remaining number of MS until it executes the command, this is here for debugging purposes
```

Now, regarding pats. I honestly have zero clue so I'll have to dig into that further.
Currently the way it works is that it looks up all of the emotes you have available identical to how [wotsit](https://github.com/goaaats/Dalamud.FindAnything) does emotes.

Hope this is helpful! c:

**Comment by cecilia-sanare** [comment]
@clytemnestra There's a known issue with the calculation for remote clients.
I haven't quite figured out what's causing it since it doesn't seem to be a timezone thing.

**Comment by cecilia-sanare** [comment]
@clytemnestra Just pushed out an update that resolves the issue with `/pet` not working among other issues!

**Comment by cecilia-sanare** [comment]
I still haven't troubleshooted that issue yet. I'll post any updates over on #6.
Also if you do `/pm pet 0` it should have the same effect as doing the negative value.

**Comment by cecilia-sanare** [comment]
@clytemnestra 

Syncing issues should be *mostly* resolved in v1.2.0.0

There will likely still be a minor delay between you and your partner when viewed from a third party, but there's very little I can do about that unfortunately outside of hosting a server purely to do syncing :c

**Comment by cecilia-sanare** [comment]
Just to verify, you've updated the plugin on all of your party members as well?

**Comment by cecilia-sanare** [comment]
Oh weird, I think an older version somehow got published under 1.2.0.1
Published a new version under 1.2.0.2

**Comment by cecilia-sanare** [comment]
Two more questions. 
1. Are y'all in a Cross World Party? (I'm assuming not, but figured I should verify anyways)
2. What DC are you on? I want to do some testing since the newer version executes emotes based upon Server Time

**Comment by cecilia-sanare** [comment]
Found a bug that *may* have been the cause of your issue. 
I only never saw it on my end because all of my clients are in the same timezone.

Pull down 1.2.0.3 and lmk if it fixes your issue! Otherwise the information above would be incredibly useful! c:

**Comment by cecilia-sanare** [comment]
I pushed out v1.2.0.4 with a minor change that could be related to your issue. Mind checking for me again?

**Comment by cecilia-sanare** [comment]
Hmm, I'll have to see if there's anything that isn't getting cleaned up properly. I'm glad its working for you now!
